### ISSUE TITLE
Converter for Plexon Offline Sorter format

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/GUI#146]
Does anyone have code to convert Open Ephys data files to the format required for Offline Sorter? Or is anyone planning to write it? This would be useful for a lot of people.

Ideally, issues like this should go in the "analysis-tools" repository, but many more people are following GUI issues right now.

**Comment by young-gyun** [comment]
Hi! I happily tried this today but receive this message.

******
>> mex ephys2plx_mex.c
/Applications/MATLAB_R2012b.app/bin/mex: line 305: gcc-4.2: command not found
/Applications/MATLAB_R2012b.app/bin/mex: line 1326: gcc-4.2: command not found

    mex: compile of ' "ephys2plx_mex.c"' failed.

Error using mex (line 206)
Unable to complete
successfully.
 
>> 
*****

Is it the problem of compiler I used? I am using Matlab 2012b in Mac, and compiler I chose is '/Applications/MATLAB_R2012b.app/bin/mexopts.sh : '

Looking forward to you reply!

**Comment by guangxingli** [comment]
Hello Young-gyun,

This error is happening probably because your MATLAB version (R2012b) dose
not support the Xcode installed on your computer. The MATLAB is expecting
GCC 4.2 to be present. This compiler was distributed with Xcode 4.0 and
4.1, but is no longer supplied as of Xcode 4.2. You could solve this
problem by applying a patch from MathWorks. The patch and detail
information could be found from here:

http://www.mathworks.com/matlabcentral/answers/94092-can-i-use-xcode-4-2-to-4-6-as-my-c-or-c-compiler-in-matlab-updated-2013-02-04

hope this helps.

Guangxing

**Comment by JMHyman** [comment]
Hi Guangxing,

I'm trying to use this converter and I keep getting this error:

Undefined function or variable 'header'.

Error in getFileHeader (line 7)
     Header=header;

Error in ephysConv (line 6)
FileHeaders{1,1}=getFileHeader([pathName ephysInfo.events_file]);

Error in ephys2plx (line 16)
ephysConv;   %get .xml file, and read information


I have the most recent version of OpenEphys and just recorded a tetrode file from the sample data.

Any help would be appreciated,
James

**Comment by Mlanzilo** [comment]
Hi Guangxing,
I have the same problem of JMHyman.
I have 2014b version of Matlab. Can you help me?
best
Marco

**Comment by mmyros** [comment]
James and Marco, this is likely due to your event files getting corrupted. If that's so, the bug is in the way recording is getting done rather than the import function. Are you using PSTH module? Try recording without it or turn off saving inside PSTH module. Aarón said that PSTH module might have some conflicting features right now (https://github.com/open-ephys/GUI/issues/262).

**Comment by JMHyman** [comment]
Thanks for the input but I don't think that's the problem.

All my files have been recorded without a PSTH module. While it looks like the problem is with the events file, I don't see any way to disable the events file.  When I comment out the events  file read lines (5-6 on EphysConv) then it goes til I get this error with the spike files:

>> ephys2plx
Error using fread
Invalid file identifier.  Use fopen to generate a valid file identifier.

Error in getFileHeader (line 5)
    hdr = fread(fid, 1024, 'char*1');

Error in ephysConv (line 17)
    FileHeaders{2,1}{i,1}=getFileHeader(SpikeFileName);

Error in ephys2plx (line 16)
ephysConv;   %get .xml file, and read information

It seems like there's been a change to the file formatting in this new version of OpenEphys or something.

**Comment by mmyros** [comment]
So this must affect the spike files as well, I have not dealt with those. At least the .continuous files are intact in my experience. I hope we can figure this out soon. In the meantime, I think I will be switching to one of the older releases.

**Comment by aacuevas** [comment]
From the looks of it, the issue with this is mainly not because of the corruption (can be in case of the events files, but not the spike ones), but because of the file format having changed (now is version .04, the ephys2plx files seem designed for version .02). What I've noticed is that the description field of the header is not up to date with all the changes, I'll fix that ASAP.

Regarding the converter itself, @guangxingli, as the original author, could you please update the format when I peoperly update the format descriptions? If not, I'll try to look at the code and do it myself.

**Comment by JMHyman** [comment]
Any updates on the file format header or .plx converters?

Thanks in advance.

**Comment by guangxingli** [comment]
Sorry, I missed the messages before. I will look into the issue and fix it
ASAP.

Guangxing

**Comment by flamesugar** [comment]
Any progress with ephys2plx.m adapt to newest GUI 0.3.5 ?  So anxious waiting...

**Comment by JMHyman** [comment]
Guangxing,

Have you had a chance to look into updating this conversion script for the new OpenEphys file format?

James

**Comment by DiegoBenusiglio** [comment]
Hello everyone,

I am using ephys2plx to convert Open Ephys data into .plx (Plexon) file readable by Offline Sorter.
So far, it works with Single Channel Mode (SE*.spikes), but it does NOT work with Stereotrode (ST*.spikes) or Tetrode mode (TT*.spikes). It returns me the following errors:

>> ephys2plx
Error using fread
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in getFileHeader (line 5)
    hdr = fread(fid, 1024, 'char*1');

Error in ephysConv (line 26)
    FileHeaders{2,1}{i,1}=getFileHeader(SpikeFileName);

Error in ephys2plx (line 15)
ephysConv;   %get .xml file, and read information
------------------------------------------------------

I am using Mac OSX 10.11.1, Matlab 2015a and Xcode 7.1.1 to compile the mex file.
Does anyone have any idea how to fix it?

Thanks in advance for your help,
Diego.

**Comment by oferyizhar** [comment]
Has anyone been able to update the converter to work with the new version of the header? We are using version 0.3.6 and it would be great if this converter would work for our data.

Thanks for your help,
Ofer

**Comment by JMHyman** [comment]
I've been using an admittedly convoluted, but functional, workaround.

It's discussed in this thread: https://github.com/open-ephys/analysis-tools/issues/7#issuecomment-159417563

Briefly, I use load_open_ehpys to get files into Matlab. Next, I use the Neuralynx script (MattoNlx) to make .ntt files. I then can open those with OFS.

**Comment by cgremel** [comment]
Hi- is anyone aware of a new update of the ephys2plx that works with the latests versions headings yet? @guangxingli @JMHyman. We can get the program compiled, but am getting back CODE:1-1 !, which may have to do with the headers? Thanks, any info would be helpful.
