### ISSUE TITLE
Analog Input Voltage Range

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#167]
From some testing I did these days, I notice that in the LFP viewer, the voltage range for the 8 analog input channels is the same as for the LFP channels (currently ranging from 50uV to 5mV). However, the analog channels have a different range (up to 5V). This makes it difficult to see the signals from the analog inputs.
Maybe a different range menu could be used for those channels?

**Comment by robertounipd** [comment]
Hi there,
I have the I/O board connected to the ±5V analog input and a signal source attached to one of the channels. I need the 16 bits to be distributed in the ±500mV range in order to effectively trace my signal, however, to my understanding, the voltage range that is settable in the LFP viewer only changes the visualization scale. Am I right? If this is the case, is there an alternative way to set the actual voltage range for the digitalization of an analog input?
Thanks in advance.

**Comment by jsiegle** [comment]
You're right, the range for the LFP Viewer only affects visualization. The ±5V input range is fixed by the hardware (although it can be changed to 0-5V by opening up the case and changing the jumper location for the ADCs). The only way to get a ±500 mV input range would be to place a 10x amplifier between your signal source and the acquisition board. Is that a possibility?

**Comment by robertounipd** [comment]
Thank you Josh. Ok, I've switched the range to 0-5V and it looks like a sufficient improvement. I wanted to make sure I wasn't missing something. Thanks again!
