### ISSUE TITLE
Wiki doc: installing zeromq from PPA on Linux

### ISSUE THREAD

**Issue by cxrodgers** [open-ephys/GUI#263]
I see that zeromq is a relatively new requirement to build the GUI from source. The current instructions are for building zeromq itself from source too. It looks like zeromq can be installed from a PPA instead, which is of course easier.
http://askubuntu.com/questions/365074/cannot-install-zeromq-package-from-chris-lea-zeromq-in-12-04
sudo add-apt-repository ppa:chris-lea/zeromq
sudo apt-get update
sudo apt-get install libzmq3-dbg libzmq3-dev libzmq3

I'm thinking about adding these instructions as an alternate installation method to the Wiki doc. It *seems* to work okay for me (that is, the GUI compiles without error), but I'm not experienced enough with the GUI to know if there is some subtle problem. Also, are we okay with recommending that people use PPAs or do we think that's too insecure?

I'm happy to update the wiki myself, but I thought I should get feedback first from someone who knows more.

**Comment by jsiegle** [comment]
Hi Chris,

You should definitely put this option on the wiki. Just add a note about checking whether the ZMQ version is compatible with the API we're using, since different package repositories are updated at different times. I'm pretty sure version 3.x is fine, but if you just install the default library (without specifying "libzmq3") it won't work, at least on the version of CentOS I'm using.
