### ISSUE TITLE
Errors while compiling with VS 2013

### ISSUE THREAD

**Issue by vncntprvst** [open-ephys/GUI#267]
This is a repost from Open Ephys Google forum, on VS 2013 support. 
https://groups.google.com/forum/#!topic/open-ephys/Nq7EfWdM8jA
I had errors compiling the newer GUI version with VS 2013. Turned out that these errors did not come up when compiling from a clean clone, instead of my synched fork's master branch (which was supposedly identical to the source repo).

**Comment by aacuevas** [comment]
It most probably is due to some VS2013 user options file. Those aren't tracked by git, as they are particular for each user, but perhaps might cause conflicts. What I'd recommend before removing and redownloading everything is cleaning the git repo. To do that execute on your local master branch:
1-"git clean -f -X" (capital X) to clean git ignored files (VS2013 user files are among them) another option is "git clean -f -d", which will delete everything that isn't in the repo (so be careful).
2- (only if you still have issues) "git reset --hard origin/master" to revert every project file to the same status as the repo. This will delete any staged or unstaged changes or local commits you might have.

If nothing of that works, then try redownloading.
