### ISSUE TITLE
sync_messages.txt empty

### ISSUE THREAD

**Issue by yves-weissenberger** [open-ephys/GUI#377]
Hi,

I'm using the open-ephys GUI to record electrophysiology signals and am using a series of TTL pulses to sync the open-ephys board with separate equipment. To do this alignment, I use the start time in the sync_messages.txt file. However, l've been looking through previous snyc_messages.txt files and noticed that many are empty, despite recording data and TTL timestamps being present. Any idea what might be causing this or how to fix this issue? Is there another place I can obtain this start time from? Many thanks!

**Comment by jsiegle** [comment]
In the latest version of the GUI, we have moved the generation of sync messages from the source processors to the Record Node. Since doing that, we have not seen any cases where `sync_messages.txt` is empty. If you're still experiencing this problem, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
