### ISSUE TITLE
Hatching error

### ISSUE THREAD

**Issue by dsmorrie** [open-ephys/GUI#378]
Hello, We have a problem opening open-ephys.
To be precise, it is data acquisition problem.
We get a screen like this, we guess it cannot get appropriate data from each channel.

![image](https://user-images.githubusercontent.com/45480302/103256188-9ca44000-49cf-11eb-9a4d-7d97efc7fcfe.png)

Is there anyone who knows the solution, or has experienced the same issue?
Thanks a lot for your help.

**Comment by jvoigts** [comment]
The hatching itself just indicates samples that are on the maximum or minimum of the amplifier input range, so you are clipping and losing data there. This can happen if you have a lot of noise and/or you have non-connected channels. If you are seeing this despite the recording setup looking correct otherwise, I'd say try debugging the analog end, grounding etc. first. Possibly try grounding individual channels and verify that they go to zero correctly.

**Comment by dsmorrie** [comment]
Thank you so much! We tried this at another computer and it worked. We would also try grounding individual channels. We really appreciate your help.
