### ISSUE TITLE
FileChoosers show up behind the GUI window on Linux

### ISSUE THREAD

**Issue by open-ephys** [open-ephys/GUI#40]
Not sure if this is specific to Linux Mint, but it's pretty annoying.

**Comment by jvoigts** [comment]
Just encountered something similar, might not be 100% related.
This is in a fresh xubuntu 15.10 install, main branch or plugin branch.
File dialog didnt show up at all, GUI stayed frozen, logged out of user session in linux, tried i3 instead of xfce with same result, went back to xfce and the file dialogs now work.

**Comment by jsiegle** [comment]
This is fixed with the upgrade to Juce v6
